---
tite: 深入理解Future机制
description: 
date: 2017-11-30
categories:
 - java并发
tags:
 - lock
 - 并发
 - 异步
---


public <T> Future<T> submit(Callable<T> task) {
        if (task == null) throw new NullPointerException();
        //构造一个RunnableFuture，为FutureTask的实例
        RunnableFuture<T> ftask = newTaskFor(task);
        execute(ftask);
        return ftask;
    }

FutureTask实例的状态转变有以下几种情况：
	NEW -> COMPLETING -> NORMAL
    NEW -> COMPLETING -> EXCEPTIONAL
    NEW -> CANCELLED
    NEW -> INTERRUPTING -> INTERRUPTED
public FutureTask(Callable<V> callable) {
        if (callable == null)
            throw new NullPointerException();
        this.callable = callable;
        //设置状态为NEW
        this.state = NEW;
    }

execute(ftask)这个方法在线程池那篇文章中分析过，主流成一样，主要是传入的command用FutureTask包装了一下,
而FutureTask实现了Runnable接口，所以当Worker启动的时候，会跑FutureTask中的run方法。
具体看一下这个run方法：
public void run() {
		//runnerOffset防止并发执行该task
		//如果task的状态不为NEW，或则runner不为null，则直接返回，说明已经有线程在执行该task或该task已经取消
        if (state != NEW ||
            !UNSAFE.compareAndSwapObject(this, runnerOffset,
                                         null, Thread.currentThread()))
            return;
        try {
            Callable<V> c = callable;
            if (c != null && state == NEW) {
                V result;
                boolean ran;
                try {
                	//运行
                    result = c.call();
                    //如果没有抛出异常则设置ran为true
                    ran = true;
                } catch (Throwable ex) {
                    result = null;
                    //抛出异常则设置ran为false，并设置exception
                    ran = false;
                    setException(ex);
                }
                if (ran)
                	//如果没有抛出异常，则设置result
                    set(result);
            }
        } finally {
            runner = null;
            int s = state;
            if (s >= INTERRUPTING)
                handlePossibleCancellationInterrupt(s);
        }
    }

接下去看一下setException(ex)和set(result)这两个方法，
注意这两个方法，如果state不为NEW，则直接返回，可能是因为该任务被取消了：
protected void setException(Throwable t) {
        if (UNSAFE.compareAndSwapInt(this, stateOffset, NEW, COMPLETING)) {
            outcome = t;
            //设置task的state为EXCEPTIONAL，这是最终态，表示以抛出异常结束
            UNSAFE.putOrderedInt(this, stateOffset, EXCEPTIONAL);
            //唤醒等待结果的线程（调用了get方法的线程）
            finishCompletion();
        }
    }
protected void set(V v) {
        if (UNSAFE.compareAndSwapInt(this, stateOffset, NEW, COMPLETING)) {
            outcome = v;
            //设置task的state为NORMAL，这是最终态，表示正常结束
            UNSAFE.putOrderedInt(this, stateOffset, NORMAL);
            finishCompletion();
        }
    }

private void finishCompletion() {
		//如果等待的线程不为null
		//WaitNode为FutureTask中的一个静态类，用来封装等待的线程队列
        for (WaitNode q; (q = waiters) != null;) {
            if (UNSAFE.compareAndSwapObject(this, waitersOffset, q, null)) {
            	//循环的唤醒等待的线程
                for (;;) {
                    Thread t = q.thread;
                    if (t != null) {
                        q.thread = null;
                        LockSupport.unpark(t);
                    }
                    WaitNode next = q.next;
                    if (next == null)
                        break;
                    q.next = null;
                    q = next;
                }
                break;
            }
        }
        //模版方法，FutureTask中为空实现
        done();
        callable = null;
    }

FutureTask中还有一个重要的方法，就是get方法，这个方法是在需要结果的时候调用，如果任务已经完成（正常和抛出异常）则会直接返回结果，
如果任务未完成，则会阻塞，进入等待队列，等待被唤醒。
public V get() throws InterruptedException, ExecutionException {
        int s = state;
        if (s <= COMPLETING)
            s = awaitDone(false, 0L);
        return report(s);
    }
该方法是上一个方法的超时版本，当超过设置的时间拿不到结果，会抛出time out异常
public V get(long timeout, TimeUnit unit)
        throws InterruptedException, ExecutionException, TimeoutException {
        if (unit == null)
            throw new NullPointerException();
        int s = state;
        //当返回的s为NEW或COMPLETING时会抛出time out异常
        if (s <= COMPLETING &&
            (s = awaitDone(true, unit.toNanos(timeout))) <= COMPLETING)
            throw new TimeoutException();
        return report(s);
    }
重点：以上两个get方法，如果线程在等待过程中被中断，都会抛出InterruptedException
private int awaitDone(boolean timed, long nanos)
        throws InterruptedException {
        //计算超时时间，如果timed为false则表明不超时
        final long deadline = timed ? System.nanoTime() + nanos : 0L;
        WaitNode q = null;
        boolean queued = false;
        for (;;) {
        	//如果线程被中断，则移除等待结点，并抛出异常
            if (Thread.interrupted()) {
                removeWaiter(q);
                throw new InterruptedException();
            }

            int s = state;
            //在入队的过程中任务完成，则直接返回任务状态的最终态
            if (s > COMPLETING) {
                if (q != null)
                    q.thread = null;
                return s;
            }
            //如果任务状态为COMPLETING，则不进入等待队列，因为从COMPLETING到最终态到时间很短
            else if (s == COMPLETING)
                Thread.yield();
            //封装当前线程
            else if (q == null)
                q = new WaitNode();
            //入队，从这里可以看出这个队列有点像栈，从头部入队
            else if (!queued)
                queued = UNSAFE.compareAndSwapObject(this, waitersOffset,
                                                     q.next = waiters, q);
            //超时机制
            else if (timed) {
                nanos = deadline - System.nanoTime();
                //超时，则返回state，由上层方法来抛出time out异常
                if (nanos <= 0L) {
                    removeWaiter(q);
                    return state;
                }
                LockSupport.parkNanos(this, nanos);
            }
            //不进行超时，则直接挂起
            else
                LockSupport.park(this);
        }
    }
private V report(int s) throws ExecutionException {
        Object x = outcome;
        //正常结束
        if (s == NORMAL)
            return (V)x;
        //任务被取消，则直接抛出CancellationException
        if (s >= CANCELLED)
            throw new CancellationException();
        //如果是因为任务在执行过程中抛出非捕获异常，则用ExecutionException封装，并抛出
        throw new ExecutionException((Throwable)x);
    }

//无论mayInterruptIfRunning为何值，只要task还没有完成，都返回true，切task的状态设置为INTERRUPTING或CANCELLED，
//调用get方法的线程永远得到CancellationException    
//如果mayInterruptIfRunning为true，则中断正在则行task的线程，如果callable在执行过程中能感知到中断，
//该中断被FutureTask中的run方法吃掉，且不设置异常结果，result永远为null
public boolean cancel(boolean mayInterruptIfRunning) {
		//如果task已经完成，则无论mayInterruptIfRunning是true还是false，都返回false
		//如果mayInterruptIfRunning为true则设置任务状态为INTERRUPTING
		//如果mayInterruptIfRunning为false则设置任务状态为CANCELLED
        if (!(state == NEW &&
              UNSAFE.compareAndSwapInt(this, stateOffset, NEW,
                  mayInterruptIfRunning ? INTERRUPTING : CANCELLED)))
            return false;
        try {    
        	//如果可以中断在执行该task的线程
            if (mayInterruptIfRunning) {
                try {
                    Thread t = runner;
                    if (t != null)
                    	//中断
                        t.interrupt();
                } finally {
                	//设置task状态的最终态为INTERRUPTED
                    UNSAFE.putOrderedInt(this, stateOffset, INTERRUPTED);
                }
            }
        } finally {
        	//唤醒等待线程
            finishCompletion();
        }
        return true;
    }
